from pathlib import Path

def replace(path, old, new):
    file = Path(path)
    text = file.read_text()
    assert text.count(old) == 1, (path, old)
    file.write_text(text.replace(old, new))

replace('src/components/trip-ticket.tsx', '      <View style={styles.main}>', '      <View testID="trip-ticket-face" style={styles.face}>\n      <View style={styles.main}>')
replace('src/components/trip-ticket.tsx', '      <View style={[styles.notch, styles.notchBottom]} />\n    </View>', '      <View style={[styles.notch, styles.notchBottom]} />\n      </View>\n    </View>')
replace('src/components/trip-ticket.tsx', '  cover: { backgroundColor:', "  face: { flex: 1, minWidth: 0, flexDirection: 'row', borderRadius: 24, overflow: 'hidden' },\n  cover: { backgroundColor:")
replace('src/components/trip-hero.tsx', '<Animated.View style={[styles.caption, { opacity }]}>', '<Animated.View testID="trip-hero-caption" style={[styles.caption, { opacity }]}>')
replace('src/utils/trip-transition.web.ts', "    if (!isTicket) {\n      name(op, root.querySelector('[data-testid=\"trip-header\"]'), 'tabi-trip-header');", "    // Foreground must not stay in root's snapshot below the named photo.\n    // The transparent ticket face includes its stub/notches, but its named\n    // cover and title are extracted into their own snapshots.\n    if (isTicket) {\n      name(op, root.querySelector('[data-testid=\"trip-ticket-face\"]'), 'tabi-trip-ticket-face');\n    } else {\n      name(op, root.querySelector('[data-testid=\"trip-hero-caption\"]'), 'tabi-trip-caption');\n      name(op, root.querySelector('[data-testid=\"trip-header\"]'), 'tabi-trip-header');")
p = Path('scripts/test-trip-transition.mjs')
p.write_text(p.read_text() + '''\n// Foreground snapshots participate in both directions, remain restricted to\n// the selected ticket, and are removed on completion or interruption.\n{\n  const f = setup();\n  const foregroundHome = () => {\n    f.home();\n    for (const id of ['a', 'b']) {\n      const ticket = f.document.getElementById(`trip-ticket-${id}`);\n      const face = f.document.createElement('div');\n      face.dataset.testid = 'trip-ticket-face';\n      face.append(...ticket.childNodes); ticket.append(face);\n    }\n  };\n  const foregroundDetail = () => {\n    f.detail();\n    const caption = f.document.createElement('div');\n    caption.dataset.testid = 'trip-hero-caption';\n    caption.textContent = 'Vienna / travel dates';\n    f.document.querySelector('main').append(caption);\n  };\n  foregroundHome();\n  f.controller.run('open', 'a', foregroundDetail); await tick();\n  assert(f.transitions[0].old.some(([element, name]) => name === 'tabi-trip-ticket-face' && element.closest('#trip-ticket-a')));\n  assert(f.transitions[0].old.every(([element]) => element.closest('#trip-ticket-a')), 'unselected ticket foreground remains in root');\n  assert(f.transitions[0].new.some(([, name]) => name === 'tabi-trip-caption'));\n  f.transitions[0].finish(); await tick();\n  assert.equal(f.named().length, 0);\n  f.controller.run('close', 'a', foregroundHome); await tick();\n  assert(f.transitions[1].old.some(([, name]) => name === 'tabi-trip-caption'));\n  assert(f.transitions[1].new.some(([, name]) => name === 'tabi-trip-ticket-face'));\n  f.document.dispatchEvent(new f.dom.window.Event('pointerdown')); await tick();\n  assert.equal(f.transitions[1].skipped, true);\n  assert.equal(f.named().length, 0, 'interrupted foreground must not retain a snapshot name');\n  f.close();\n}\nconsole.log('Trip foreground: open/close capture, selected ticket isolation and interruption cleanup passed.');\n''')
